# Generated by Django 3.0.7 on 2020-06-26 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='artistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='auxiliary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contracting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='engineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='etf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='financing_bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='non_metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='other_financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='supply_elec_gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='technical_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='water_transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wholesale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
    ]
