# Generated by Django 3.0.7 on 2020-07-01 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_app_computer_artistic_auxiliary_banks_cement_chemical_contracting_drug_engineering_estate_etf_financ'),
    ]

    operations = [
        migrations.CreateModel(
            name='tanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='telecommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('data', models.TextField()),
            ],
        ),
    ]
