# Generated by Django 3.0.7 on 2020-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_tanning_telecommunication'),
    ]

    operations = [
        migrations.CreateModel(
            name='namadtomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namad', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
