# Generated by Django 3.0.7 on 2020-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_namadtomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali', models.CharField(max_length=250)),
                ('miladi', models.CharField(max_length=100)),
            ],
        ),
    ]
