# Generated by Django 3.0.7 on 2020-08-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_active_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='initial_public_offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namad', models.CharField(max_length=250)),
            ],
        ),
    ]
