# Generated by Django 3.0.7 on 2020-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_initial_public_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='sf',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
